export type Priority = 'LOW' | 'MEDIUM' | 'HIGH'
export interface Findings { crown_condition: string; crown_loss: boolean; dead_branches: boolean; broken_limbs: boolean; trunk_damage: boolean; possible_cavity: boolean; leaning: string; fungal_growth: string; base_or_root_damage: boolean; other_anomalies: string[]; confidence: number; summary: string }
export interface GroundContext { provider: 'MAPILLARY' | 'GOOGLE_STREET_VIEW'; source: string; captureDate?: string; imageUrl: string; freshness: 'RECENT' | 'AGING' | 'HISTORICAL' | 'UNKNOWN' }
export interface AerialContext { imageUrl: string; source: string; captureDate?: string; bbox: number[] }
export interface ApproximateAddress { address: string; label: string }
export interface Result { location: { latitude: number; longitude: number }; submitted_at: string; aerial?: { image_url: string; source: string; capture_date?: string; bbox: number[] }; street_view?: { source: string; capture_date?: string; copyright?: string }; ground_context?: { provider: string; source: string; capture_date?: string; freshness: string }; findings: Findings; warning_signs: string[]; score: number; priority: Priority; recommendation: string; disclaimer: string }
export interface AreaCandidate { asset_id?: string; location: { latitude: number; longitude: number }; priority: Priority; score: number; warning_signs: string[]; summary: string; confidence: number; source: 'HRM_INVENTORY' | 'AERIAL_DETECTION'; discovery_evidence?: string; street_view_available: boolean; ground_context_provider?: 'MAPILLARY' | 'GOOGLE_STREET_VIEW'; ground_context_date?: string; ground_context_freshness?: 'RECENT' | 'AGING' | 'HISTORICAL' | 'UNKNOWN' }
export interface SatelliteContext { source: string; latest_observation?: string; previous_observation?: string; latest_radar_observation?: string; latest_optical_observation?: string; cloud_cover?: number; status: 'AVAILABLE' | 'UNAVAILABLE'; scope: string }
export interface AreaScreening { bounds: { south: number; west: number; north: number; east: number }; candidates_found: number; candidate_source: string; inventory_candidates_found: number; aerial_candidates_found: number; aerial_discovery_status: string; satellite_context?: SatelliteContext; screened: AreaCandidate[]; disclaimer: string }
